from sel_acl.objs import ACE, ACL

correct_groups = (
    ["dst_grp2", "src_grp1", "dst_grp1"],
    ["dst_port2", "src_port1", "dst_port1"],
)

correct_overlaps = [
    (" remark ### MY REMARK", " remark ### MY REMARK"),
    (" permit ip 10.1.1.0/24 99.99.99.0/24 ", " permit ip 10.1.1.0/24 99.99.99.0/24 "),
    (
        " permit ip 10.1.1.0/24 99.99.99.0/24 ",
        " permit ip addrgroup src_grp2 99.99.99.0/24 ",
    ),
    (
        " permit ip 10.1.1.0/24 99.99.99.0/24 ",
        " permit ip 10.1.1.0/24 addrgroup dst_grp4 ",
    ),
    (
        " permit ip 10.1.1.0/24 99.99.99.0/24 eq 80 ",
        " permit ip 10.1.1.0/24 99.99.99.0/24 range 79 81 ",
    ),
    (
        " permit ip addrgroup src_grp1 99.99.99.0/24 ",
        " permit ip 10.1.1.0/24 99.99.99.0/24 ",
    ),
    (
        " permit ip addrgroup src_grp1 99.99.99.0/24 ",
        " permit ip addrgroup src_grp2 99.99.99.0/24 ",
    ),
    (
        " permit ip addrgroup src_grp1 99.99.99.0/24 ",
        " permit ip 10.1.1.0/24 addrgroup dst_grp4 ",
    ),
    (
        " permit tcp addrgroup src_grp2 99.99.99.0/24 eq 52 ",
        " permit tcp addrgroup src_grp2 99.99.99.0/24 eq 52 ",
    ),
    (
        " permit tcp addrgroup src_grp1 portgroup src_port1 10.1.6.0/24 ",
        " permit tcp 10.1.1.0/25 range 400 1534 10.1.6.0/24 ",
    ),
    (
        " permit tcp 10.1.1.0/24 10.1.6.0/24 portgroup dst_port1 ",
        " permit tcp 10.1.1.0/24 10.1.6.0/24 range 400 1434 ",
    ),
]

dns_acl_output = "ip access-list DNS-Tests\n remark ### From: one.one.one.one\tTo: dns.google\n permit ip 1.1.1.1/32 8.8.8.8/32 \n remark ### From: media-router-fp74.prod.media.vip.gq1.yahoo.com\n permit ip 98.137.11.163/32 10.1.6.0/24 \n remark ### To: dns9.quad9.net\n permit ip 10.1.1.0/24 9.9.9.9/32 \n"

vlan1_contracts = [
        {
            "acl_name": "From-Vlan1",
            "action": "permit",
            "protocol": "tcp",
            "src_aci": "",
            "src_tenant": "tenant1",
            "src_epg": "vlan1_EPG",
            "src_application": "vlan1_ap",
            "src_address": "10.1.1.0/24",
            "src_port": "443",
            "src_portgroup": None,
            "dst_tenant": "tenant1",
            "dst_epg": "vlan2_EPG",
            "dst_application": "vlan2_ap",
            "dst_aci": "",
            "dst_address": "10.1.2.0/25",
            "dst_port": "",
            "dst_portgroup": None,
            "flags": None,
            "remark": "",
            "contract": "",
            "access-list": "",
            "ace": "",
            "Notes": "",
            "Completed": "",
        },
        {
            "acl_name": "From-Vlan1",
            "action": "permit",
            "protocol": "ip",
            "src_aci": "",
            "src_tenant": "tenant1",
            "src_epg": "vlan1_EPG",
            "src_application": "vlan1_ap",
            "src_address": "10.1.1.0/24",
            "src_port": "",
            "src_portgroup": None,
            "dst_tenant": "tenant1",
            "dst_epg": "vlan2_EPG",
            "dst_application": "vlan2_ap",
            "dst_aci": "",
            "dst_address": "dst_grp2",
            "dst_port": "443 - 447",
            "dst_portgroup": "dst_port2",
            "flags": None,
            "remark": "",
            "contract": "",
            "access-list": "",
            "ace": "",
            "Notes": "",
            "Completed": "",
        },
    ]

vlan2_contracts = [
        {
            "acl_name": "From-Vlan2",
            "action": "permit",
            "protocol": "ip",
            "src_aci": "",
            "src_tenant": "tenant1",
            "src_epg": "vlan2_EPG",
            "src_application": "vlan2_ap",
            "src_address": "10.1.1.0/24",
            "src_port": "",
            "src_portgroup": None,
            "dst_tenant": "tenant1",
            "dst_epg": "vlan1_EPG",
            "dst_application": "vlan1_ap",
            "dst_aci": "",
            "dst_address": "dst_grp1",
            "dst_port": "443,1433",
            "dst_portgroup": "dst_port1",
            "flags": None,
            "remark": "",
            "contract": "",
            "access-list": "",
            "ace": "",
            "Notes": "",
            "Completed": "",
        }
    ]
vlan3_contracts = [
        {
            "acl_name": "From-Vlan3",
            "action": "permit",
            "protocol": "udp",
            "src_aci": "",
            "src_tenant": "tenant2",
            "src_epg": "vlan3_EPG",
            "src_application": "vlan3_ap",
            "src_address": "10.1.1.5/32",
            "src_port": "",
            "src_portgroup": None,
            "dst_tenant": "tenant2",
            "dst_epg": "vlan4_EPG",
            "dst_application": "vlan4_ap",
            "dst_aci": "",
            "dst_address": "10.1.4.0/25",
            "dst_port": "",
            "dst_portgroup": None,
            "flags": None,
            "remark": "### to vlan4",
            "contract": "",
            "access-list": "",
            "ace": "",
            "Notes": "",
            "Completed": "",
        },
        {
            "acl_name": "From-Vlan3",
            "action": "permit",
            "protocol": "ip",
            "src_aci": "",
            "src_tenant": "tenant2",
            "src_epg": "vlan3_EPG",
            "src_application": "vlan3_ap",
            "src_address": "10.1.1.5/32",
            "src_port": "",
            "src_portgroup": None,
            "dst_tenant": "tenant2",
            "dst_epg": "vlan5_EPG",
            "dst_application": "vlan5_ap",
            "dst_aci": "",
            "dst_address": "10.1.5.0/24",
            "dst_port": "",
            "dst_portgroup": None,
            "flags": None,
            "remark": "### to vlan5",
            "contract": "",
            "access-list": "",
            "ace": "",
            "Notes": "",
            "Completed": "",
        }
    ]

vlan4_contracts = [
        {
            "acl_name": "From-Vlan4",
            "action": "permit",
            "protocol": "ip",
            "src_aci": "",
            "src_tenant": "tenant2",
            "src_epg": "vlan4_EPG",
            "src_application": "vlan4_ap",
            "src_address": "10.1.1.5/32",
            "src_port": "",
            "src_portgroup": None,
            "dst_tenant": "tenant2",
            "dst_epg": "vlan5_EPG",
            "dst_application": "vlan5_ap",
            "dst_aci": "",
            "dst_address": "10.1.5.0/24",
            "dst_port": "",
            "dst_portgroup": None,
            "flags": None,
            "remark": "### to vlan5",
            "contract": "",
            "access-list": "",
            "ace": "",
            "Notes": "",
            "Completed": "",
        }
    ]
vlan5_contracts = [
        {
            "acl_name": "From-Vlan5",
            "action": "permit",
            "protocol": "udp",
            "src_aci": "",
            "src_tenant": "tenant2",
            "src_epg": "vlan5_EPG",
            "src_application": "vlan5_ap",
            "src_address": "10.1.1.5/32",
            "src_port": "",
            "src_portgroup": None,
            "dst_tenant": "tenant2",
            "dst_epg": "vlan4_EPG",
            "dst_application": "vlan4_ap",
            "dst_aci": "",
            "dst_address": "10.1.4.0/25",
            "dst_port": "",
            "dst_portgroup": None,
            "flags": None,
            "remark": "### to vlan4",
            "contract": "",
            "access-list": "",
            "ace": "",
            "Notes": "",
            "Completed": "",
        }
    ]
vlan6_contracts = []
vlan7_contracts = []

test_nexus_acl_output = "ip access-list Nexus-From-Vlan1\n 10 remark ### Allow EIGRP\n 20 permit eigrp 10.26.0.0/16 10.26.0.0/16 \n 30 permit eigrp 10.26.0.0/16 224.0.0.10/32 \n 40 permit eigrp 224.0.0.10/32 10.26.0.0/16 \n 50 remark ### Allow DHCP\n 60 permit udp 10.0.0.0/8 eq bootpc addrgroup DHCP-Svrs eq bootps \n 70 permit udp 10.0.0.0/8 eq bootps addrgroup DHCP-Svrs eq bootps \n 80 permit udp addrgroup DHCP-Svrs eq bootps 10.0.0.0/8 eq bootpc \n 90 permit udp addrgroup DHCP-Svrs eq bootps 10.0.0.0/8 eq bootps \n 100 remark ### Allow DNS\n"

test_acl = ACL(
    name="From-Vlan1",
    acl=None,
    aces=[
        ACE(
            remark="### MY REMARK",
            action=None,
            protocol=None,
            src_group=None,
            src_wld=None,
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="ip",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld="99.99.99.0 0.0.0.255",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr="99.99.99.0/24",
        ),
        ACE(
            remark="### to vlan2",
            action=None,
            protocol=None,
            src_group=None,
            src_wld=None,
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld="10.1.2.0 0.0.0.255",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match="eq",
            dst_port_start=None,
            dst_port_end=None,
            dst_port="443",
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr="10.1.2.0/24",
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="443",
            dst_group=None,
            dst_wld="10.1.2.0 0.0.0.127",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr="10.1.2.0/25",
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="ip",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group="dst_grp2",
            dst_wld=None,
            dst_host=None,
            dst_any=None,
            dst_portgroup="dst_port2",
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="icmp",
            src_group=None,
            src_wld=None,
            src_host=None,
            src_any="any",
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host=None,
            dst_any="any",
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark="### to vlan3",
            action=None,
            protocol=None,
            src_group=None,
            src_wld=None,
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="443",
            dst_group=None,
            dst_wld="10.1.3.32 0.0.0.31",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag="established",
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr="10.1.3.32/27",
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="443",
            dst_group=None,
            dst_wld="10.1.3.0 0.0.0.255",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag="established",
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr="10.1.3.0/24",
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="udp",
            src_group=None,
            src_wld=None,
            src_host="10.1.1.5",
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host="10.1.3.5",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark="### to any",
            action=None,
            protocol=None,
            src_group=None,
            src_wld=None,
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="deny",
            protocol="ip",
            src_group=None,
            src_wld=None,
            src_host=None,
            src_any="any",
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host=None,
            dst_any="any",
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log="log",
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="udp",
            src_group=None,
            src_wld=None,
            src_host="0.0.0.0",
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="bootpc",
            dst_group=None,
            dst_wld=None,
            dst_host="255.255.255.255",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match="eq",
            dst_port_start=None,
            dst_port_end=None,
            dst_port="bootps",
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark="### to vlan4",
            action=None,
            protocol=None,
            src_group=None,
            src_wld=None,
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="udp",
            src_group=None,
            src_wld=None,
            src_host="10.1.1.5",
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld="10.1.4.0 0.0.0.127",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr="10.1.4.0/25",
        ),
        ACE(
            remark="### to vlan5",
            action=None,
            protocol=None,
            src_group=None,
            src_wld=None,
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="ip",
            src_group=None,
            src_wld=None,
            src_host="10.1.1.5",
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld="10.1.5.0 0.0.0.255",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr="10.1.5.0/24",
        ),
        ACE(
            remark="### to vlan6",
            action=None,
            protocol=None,
            src_group=None,
            src_wld=None,
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="ip",
            src_group="src_grp1",
            src_wld=None,
            src_host=None,
            src_any=None,
            src_portgroup="src_port1",
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host="10.1.6.5",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="ip",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group="dst_grp1",
            dst_wld=None,
            dst_host=None,
            dst_any=None,
            dst_portgroup="dst_port1",
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="443",
            dst_group=None,
            dst_wld=None,
            dst_host="10.1.6.5",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag="established",
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="10933",
            dst_group=None,
            dst_wld=None,
            dst_host="10.1.6.5",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag="established",
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="443",
            dst_group=None,
            dst_wld=None,
            dst_host="10.1.6.5",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match="eq",
            dst_port_start=None,
            dst_port_end=None,
            dst_port="777",
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="443",
            dst_group=None,
            dst_wld=None,
            dst_host="10.1.6.5",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match="eq",
            dst_port_start=None,
            dst_port_end=None,
            dst_port="888",
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="10933",
            dst_group=None,
            dst_wld=None,
            dst_host="10.1.6.5",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match="eq",
            dst_port_start=None,
            dst_port_end=None,
            dst_port="777",
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="10933",
            dst_group=None,
            dst_wld=None,
            dst_host="10.1.6.5",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match="eq",
            dst_port_start=None,
            dst_port_end=None,
            dst_port="888",
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld="10.1.6.0 0.0.0.255",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match="eq",
            dst_port_start=None,
            dst_port_end=None,
            dst_port="777",
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr="10.1.6.0/24",
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld="10.1.6.0 0.0.0.255",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match="eq",
            dst_port_start=None,
            dst_port_end=None,
            dst_port="888",
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr="10.1.6.0/24",
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld="10.1.6.0 0.0.0.255",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match="range",
            dst_port_start="500",
            dst_port_end="600",
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr="10.1.6.0/24",
        ),
    ],
)
