from sel_acl.objs import ACE, ACL

correct_groups = (
    ["dst_grp2", "src_grp1", "dst_grp1"],
    ["dst_port2", "src_port1", "dst_port1"],
)

correct_overlaps = [
    (" ### MY REMARK", " ### MY REMARK"),
    (" permit ip 10.1.1.0/24 99.99.99.0/24 ", " permit ip 10.1.1.0/24 99.99.99.0/24 "),
    (
        " permit ip 10.1.1.0/24 99.99.99.0/24 ",
        " permit ip addrgroup src_grp2 99.99.99.0/24 ",
    ),
    (
        " permit ip 10.1.1.0/24 99.99.99.0/24 ",
        " permit ip 10.1.1.0/24 addrgroup dst_grp4 ",
    ),
    (
        " permit ip 10.1.1.0/24 99.99.99.0/24 eq 80 ",
        " permit ip 10.1.1.0/24 99.99.99.0/24 range 79 81 ",
    ),
    (
        " permit ip addrgroup src_grp1 99.99.99.0/24 ",
        " permit ip 10.1.1.0/24 99.99.99.0/24 ",
    ),
    (
        " permit ip addrgroup src_grp1 99.99.99.0/24 ",
        " permit ip addrgroup src_grp2 99.99.99.0/24 ",
    ),
    (
        " permit ip addrgroup src_grp1 99.99.99.0/24 ",
        " permit ip 10.1.1.0/24 addrgroup dst_grp4 ",
    ),
    (
        " permit tcp addrgroup src_grp2 99.99.99.0/24 eq 52 ",
        " permit tcp addrgroup src_grp2 99.99.99.0/24 eq 52 ",
    ),
    (
        " permit tcp addrgroup src_grp1 portgroup src_port1 10.1.6.0/24 ",
        " permit tcp 10.1.1.0/25 range 400 1534 10.1.6.0/24 ",
    ),
    (
        " permit tcp 10.1.1.0/24 10.1.6.0/24 portgroup dst_port1 ",
        " permit tcp 10.1.1.0/24 10.1.6.0/24 range 400 1434 ",
    ),
]

vlan1_contracts = [
    {
        "acl_name": "From-Vlan1",
        "action": "permit",
        "protocol": "tcp",
        "src_aci": "",
        "src_tenant": "tenant1",
        "src_epg": "EPG-vlan1",
        "src_address": "10.1.1.0/24",
        "src_port": "443",
        "dst_tenant": "tenant1",
        "dst_epg": "EPG-vlan2",
        "dst_aci": "",
        "dst_address": "10.1.2.0/25",
        "dst_port": "",
        "flags": None,
        "contract": "",
        "access-list": "",
        "ace": "",
        "Notes": "",
        "Completed": "",
    },
    {
        "acl_name": "From-Vlan1",
        "action": "permit",
        "protocol": "ip",
        "src_aci": "",
        "src_tenant": "tenant1",
        "src_epg": "EPG-vlan1",
        "src_address": "10.1.1.0/24",
        "src_port": "",
        "dst_tenant": "tenant1",
        "dst_epg": "EPG-vlan2",
        "dst_aci": "",
        "dst_address": "dst_grp2",
        "dst_port": "dst_port2",
        "flags": None,
        "contract": "",
        "access-list": "",
        "ace": "",
        "Notes": "",
        "Completed": "",
    },
]
vlan2_contracts = [
    {
        "acl_name": "From-Vlan2",
        "action": "permit",
        "protocol": "ip",
        "src_aci": "",
        "src_tenant": "tenant1",
        "src_epg": "EPG-vlan2",
        "src_address": "10.1.1.0/24",
        "src_port": "",
        "dst_tenant": "tenant1",
        "dst_epg": "EPG-vlan1",
        "dst_aci": "",
        "dst_address": "dst_grp1",
        "dst_port": "dst_port1",
        "flags": None,
        "contract": "",
        "access-list": "",
        "ace": "",
        "Notes": "",
        "Completed": "",
    }
]
vlan3_contracts = [
    {
        "acl_name": "From-Vlan3",
        "action": "permit",
        "protocol": "udp",
        "src_aci": "",
        "src_tenant": "tenant2",
        "src_epg": "EPG-vlan3",
        "src_address": "10.1.1.5/32",
        "src_port": "",
        "dst_tenant": "tenant2",
        "dst_epg": "EPG-vlan!4",
        "dst_aci": "",
        "dst_address": "10.1.4.0/25",
        "dst_port": "",
        "flags": None,
        "contract": "",
        "access-list": "",
        "ace": "",
        "Notes": "",
        "Completed": "",
    },
    {
        "acl_name": "From-Vlan3",
        "action": "permit",
        "protocol": "ip",
        "src_aci": "",
        "src_tenant": "tenant2",
        "src_epg": "EPG-vlan3",
        "src_address": "10.1.1.5/32",
        "src_port": "",
        "dst_tenant": "tenant2",
        "dst_epg": "EPG-vlan5",
        "dst_aci": "",
        "dst_address": "10.1.5.0/24",
        "dst_port": "",
        "flags": None,
        "contract": "",
        "access-list": "",
        "ace": "",
        "Notes": "",
        "Completed": "",
    },
]
vlan4_contracts = [
    {
        "acl_name": "From-Vlan4",
        "action": "permit",
        "protocol": "tcp",
        "src_aci": "",
        "src_tenant": "tenant2",
        "src_epg": "EPG-vlan!4",
        "src_address": "10.1.1.0/24",
        "src_port": "443",
        "dst_tenant": "tenant2",
        "dst_epg": "EPG-vlan3",
        "dst_aci": "",
        "dst_address": "10.1.3.32/27",
        "dst_port": "",
        "flags": "established",
        "contract": "",
        "access-list": "",
        "ace": "",
        "Notes": "",
        "Completed": "",
    },
    {
        "acl_name": "From-Vlan4",
        "action": "permit",
        "protocol": "ip",
        "src_aci": "",
        "src_tenant": "tenant2",
        "src_epg": "EPG-vlan!4",
        "src_address": "10.1.1.5/32",
        "src_port": "",
        "dst_tenant": "tenant2",
        "dst_epg": "EPG-vlan5",
        "dst_aci": "",
        "dst_address": "10.1.5.0/24",
        "dst_port": "",
        "flags": None,
        "contract": "",
        "access-list": "",
        "ace": "",
        "Notes": "",
        "Completed": "",
    },
]
vlan5_contracts = [
    {
        "acl_name": "From-Vlan5",
        "action": "permit",
        "protocol": "tcp",
        "src_aci": "",
        "src_tenant": "tenant2",
        "src_epg": "EPG-vlan5",
        "src_address": "10.1.1.0/24",
        "src_port": "443",
        "dst_tenant": "tenant2",
        "dst_epg": "EPG-vlan3",
        "dst_aci": "",
        "dst_address": "10.1.3.32/27",
        "dst_port": "",
        "flags": "established",
        "contract": "",
        "access-list": "",
        "ace": "",
        "Notes": "",
        "Completed": "",
    },
    {
        "acl_name": "From-Vlan5",
        "action": "permit",
        "protocol": "udp",
        "src_aci": "",
        "src_tenant": "tenant2",
        "src_epg": "EPG-vlan5",
        "src_address": "10.1.1.5/32",
        "src_port": "",
        "dst_tenant": "tenant2",
        "dst_epg": "EPG-vlan!4",
        "dst_aci": "",
        "dst_address": "10.1.4.0/25",
        "dst_port": "",
        "flags": None,
        "contract": "",
        "access-list": "",
        "ace": "",
        "Notes": "",
        "Completed": "",
    },
]
vlan6_contracts = []
vlan7_contracts = []

test_acl = ACL(
    name="From-Vlan1",
    acl=None,
    aces=[
        ACE(
            remark="### MY REMARK",
            action=None,
            protocol=None,
            src_group=None,
            src_wld=None,
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="ip",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld="99.99.99.0 0.0.0.255",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr="99.99.99.0/24",
        ),
        ACE(
            remark="### to vlan2",
            action=None,
            protocol=None,
            src_group=None,
            src_wld=None,
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld="10.1.2.0 0.0.0.255",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match="eq",
            dst_port_start=None,
            dst_port_end=None,
            dst_port="443",
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr="10.1.2.0/24",
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="443",
            dst_group=None,
            dst_wld="10.1.2.0 0.0.0.127",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr="10.1.2.0/25",
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="ip",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group="dst_grp2",
            dst_wld=None,
            dst_host=None,
            dst_any=None,
            dst_portgroup="dst_port2",
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="icmp",
            src_group=None,
            src_wld=None,
            src_host=None,
            src_any="any",
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host=None,
            dst_any="any",
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark="### to vlan3",
            action=None,
            protocol=None,
            src_group=None,
            src_wld=None,
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="443",
            dst_group=None,
            dst_wld="10.1.3.32 0.0.0.31",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag="established",
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr="10.1.3.32/27",
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="443",
            dst_group=None,
            dst_wld="10.1.3.0 0.0.0.255",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag="established",
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr="10.1.3.0/24",
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="udp",
            src_group=None,
            src_wld=None,
            src_host="10.1.1.5",
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host="10.1.3.5",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark="### to any",
            action=None,
            protocol=None,
            src_group=None,
            src_wld=None,
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="deny",
            protocol="ip",
            src_group=None,
            src_wld=None,
            src_host=None,
            src_any="any",
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host=None,
            dst_any="any",
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log="log",
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="udp",
            src_group=None,
            src_wld=None,
            src_host="0.0.0.0",
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="bootpc",
            dst_group=None,
            dst_wld=None,
            dst_host="255.255.255.255",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match="eq",
            dst_port_start=None,
            dst_port_end=None,
            dst_port="bootps",
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark="### to vlan4",
            action=None,
            protocol=None,
            src_group=None,
            src_wld=None,
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="udp",
            src_group=None,
            src_wld=None,
            src_host="10.1.1.5",
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld="10.1.4.0 0.0.0.127",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr="10.1.4.0/25",
        ),
        ACE(
            remark="### to vlan5",
            action=None,
            protocol=None,
            src_group=None,
            src_wld=None,
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="ip",
            src_group=None,
            src_wld=None,
            src_host="10.1.1.5",
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld="10.1.5.0 0.0.0.255",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr="10.1.5.0/24",
        ),
        ACE(
            remark="### to vlan6",
            action=None,
            protocol=None,
            src_group=None,
            src_wld=None,
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="ip",
            src_group="src_grp1",
            src_wld=None,
            src_host=None,
            src_any=None,
            src_portgroup="src_port1",
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host="10.1.6.5",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="ip",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group="dst_grp1",
            dst_wld=None,
            dst_host=None,
            dst_any=None,
            dst_portgroup="dst_port1",
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="443",
            dst_group=None,
            dst_wld=None,
            dst_host="10.1.6.5",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag="established",
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="10933",
            dst_group=None,
            dst_wld=None,
            dst_host="10.1.6.5",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag="established",
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="443",
            dst_group=None,
            dst_wld=None,
            dst_host="10.1.6.5",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match="eq",
            dst_port_start=None,
            dst_port_end=None,
            dst_port="777",
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="443",
            dst_group=None,
            dst_wld=None,
            dst_host="10.1.6.5",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match="eq",
            dst_port_start=None,
            dst_port_end=None,
            dst_port="888",
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="10933",
            dst_group=None,
            dst_wld=None,
            dst_host="10.1.6.5",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match="eq",
            dst_port_start=None,
            dst_port_end=None,
            dst_port="777",
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="10933",
            dst_group=None,
            dst_wld=None,
            dst_host="10.1.6.5",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match="eq",
            dst_port_start=None,
            dst_port_end=None,
            dst_port="888",
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld="10.1.6.0 0.0.0.255",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match="eq",
            dst_port_start=None,
            dst_port_end=None,
            dst_port="777",
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr="10.1.6.0/24",
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld="10.1.6.0 0.0.0.255",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match="eq",
            dst_port_start=None,
            dst_port_end=None,
            dst_port="888",
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr="10.1.6.0/24",
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.1.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld="10.1.6.0 0.0.0.255",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match="range",
            dst_port_start="500",
            dst_port_end="600",
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.1.1.0/24",
            dst_cidr="10.1.6.0/24",
        ),
    ],
)
