from rich.pretty import pprint

from sel_acl.objs import ACE, ACL
from sel_acl.utils import get_acl_from_file

test_acl_correct = ACL(
    name="my-test-acl",
    acl=None,
    aces=[
        ACE(
            remark="remark ### MY REMARK",
            action=None,
            protocol=None,
            src_group=None,
            src_wld=None,
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="ip",
            src_group=None,
            src_wld="10.0.0.0 0.255.255.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld="10.1.0.0 0.0.255.255",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.0.0.0/8",
            dst_cidr="10.1.0.0/16",
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.0.0.0 0.255.255.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld="10.1.0.0 0.0.255.255",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.0.0.0/8",
            dst_cidr="10.1.0.0/16",
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="udp",
            src_group=None,
            src_wld="10.0.0.0 0.255.255.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld="10.1.0.0 0.0.255.255",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.0.0.0/8",
            dst_cidr="10.1.0.0/16",
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="icmp",
            src_group=None,
            src_wld="10.0.0.0 0.255.255.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld="10.1.0.0 0.0.255.255",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.0.0.0/8",
            dst_cidr="10.1.0.0/16",
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.0.0.0 0.255.255.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="443",
            dst_group=None,
            dst_wld="10.1.0.0 0.0.255.255",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.0.0.0/8",
            dst_cidr="10.1.0.0/16",
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.0.0.0 0.255.255.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="443",
            dst_group=None,
            dst_wld="10.1.0.0 0.0.255.255",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match="eq ",
            dst_port_start=None,
            dst_port_end=None,
            dst_port="443",
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr="10.0.0.0/8",
            dst_cidr="10.1.0.0/16",
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="ip",
            src_group=None,
            src_wld=None,
            src_host="host 10.10.10.10",
            src_any=None,
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host="host 11.11.11.11",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log="log",
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="deny",
            protocol="ip",
            src_group=None,
            src_wld=None,
            src_host=None,
            src_any="any",
            src_portgroup=None,
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host=None,
            dst_any="any",
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log="log",
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="udp",
            src_group=None,
            src_wld=None,
            src_host="host 0.0.0.0",
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="bootpc",
            dst_group=None,
            dst_wld=None,
            dst_host="host 255.255.255.255",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match="eq ",
            dst_port_start=None,
            dst_port_end=None,
            dst_port="bootps",
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group="addrgroup source_object_group",
            src_wld=None,
            src_host=None,
            src_any=None,
            src_portgroup="portgroup source_portgroup",
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host="host 8.8.8.8",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag=None,
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group="addrgroup source_object_group",
            src_wld=None,
            src_host=None,
            src_any=None,
            src_portgroup="portgroup source_portgroup",
            src_port_match=None,
            src_port_start=None,
            src_port_end=None,
            src_port=None,
            dst_group=None,
            dst_wld=None,
            dst_host="host 8.8.8.8",
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag="established",
            icmp_type=None,
            log=None,
            src_cidr=None,
            dst_cidr=None,
        ),
        ACE(
            remark=None,
            action="permit",
            protocol="tcp",
            src_group=None,
            src_wld="10.105.1.0 0.0.0.255",
            src_host=None,
            src_any=None,
            src_portgroup=None,
            src_port_match="eq",
            src_port_start=None,
            src_port_end=None,
            src_port="443 10933",
            dst_group=None,
            dst_wld="10.105.113.128 0.0.0.127",
            dst_host=None,
            dst_any=None,
            dst_portgroup=None,
            dst_port_match=None,
            dst_port_start=None,
            dst_port_end=None,
            dst_port=None,
            flags_match=None,
            tcp_flag="established",
            icmp_type=None,
            log=None,
            src_cidr="10.105.1.0/24",
            dst_cidr="10.105.113.128/25",
        ),
    ],
)


def test_regex():
    filename = "./tests/acl_tests.txt"
    test_acl = get_acl_from_file(filename, "my-test-acl")
    test_acl.acl = None

    pprint(test_acl)
    # assert test_acl == test_acl_correct


if __name__ == "__main__":
    test_regex()
